apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/victoria-metrics.yaml
  - apps/loki.yaml
  - apps/blackbox-exporter.yaml
  - apps/alloy.yaml
  - manifests/ingressroutes.yaml
  - manifests/alertmanager-secrets.yaml
  - manifests/alertmanager-ingest.yaml
  - manifests/alertmanager-config.yaml
  - manifests/probes.yaml
  - manifests/rules.yaml
  - manifests/cron-alert-analyzer.yaml
  - manifests/dashboards.yaml
