apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  labels:
    e-dani.com/tier: infra
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.8.1
      helm:
        releaseName: alloy
        valueFiles:
          - $values/alloy/values.yaml
    - repoURL: https://github.com/pocharlies/k8s-observability-pocharlies
      targetRevision: deploy/prod
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
