apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.79.0
      helm:
        releaseName: vm
        valueFiles:
          - $values/victoria-metrics/values.yaml
    - repoURL: https://github.com/pocharlies/k8s-observability-pocharlies
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
